- name: install apache and php
  package:
    name:
      - "{{ apache_package }}"
      - "{{ php_package }}"
    state: latest
    update_cache: yes
- name: copy default html file for site
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: "{{ www_root }}/index.html"
    owner: root
    group: root
  notify: restart_apache