version: "3.8"

services:
  ansible:
    build:
      context: .
      dockerfile: ./Dockerfile-ansible
    image: local/ansible:latest
    container_name: ansible
    tty: true
    environment:
      - ANSIBLE_CONFIG=/data/ansible/ansible.cfg
    volumes:
      - ..:/data
    networks:
      - ansible

  ubuntu1:
    build:
      context: .
      dockerfile: ./Dockerfile-ubuntu
    image: local/ubuntu:ssh
    container_name: ubuntu1
    tty: true
    networks:
      - ansible
    
  ubuntu2:
    build:
      context: .
      dockerfile: ./Dockerfile-ubuntu
    image: local/ubuntu:ssh
    container_name: ubuntu2
    tty: true
    networks:
      - ansible

  ubuntu3:
    build:
      context: .
      dockerfile: ./Dockerfile-ubuntu
    image: local/ubuntu:ssh
    container_name: ubuntu3
    tty: true
    networks:
      - ansible
  
  alpine1:
    build:
      context: .
      dockerfile: ./Dockerfile-alpine
    image: local/alpine:ssh
    container_name: alpine1
    tty: true
    networks:
      - ansible

networks:
  ansible:
    driver: bridge