FROM quay.io/centos/centos:stream9

RUN yum update && yum install openssh-server sudo openssl -y

RUN groupadd sshgroup && useradd -ms /bin/bash -p $(openssl passwd -1 "ansible") -g sshgroup -G wheel ansible

# Create sshuser directory in home
RUN mkdir -p /home/ansible/.ssh
# Copy the ssh public key in the authorized_keys file. The idkey.pub below is a public key file you get from ssh-keygen. They are under ~/.ssh directory by default.
COPY id_ansible.pub /home/ansible/.ssh/authorized_keys
# change ownership of the key file. 
RUN chown ansible:sshgroup /home/ansible/.ssh/authorized_keys && chmod 600 /home/ansible/.ssh/authorized_keys

RUN /usr/bin/ssh-keygen -A 

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]
