version: "3.8"

services:
  ansible:
    image: cytopia/ansible:latest
    container_name: ansible
    tty: true
    networks:
      - ansible

  ubuntu1:
    image: ubuntu:latest
    container_name: ubuntu1
    tty: true
    networks:
      - ansible
    
  ubuntu2:
    image: ubuntu:latest
    container_name: ubuntu2
    tty: true
    networks:
      - ansible

  ubuntu3:
    image: ubuntu:latest
    container_name: ubuntu3
    tty: true
    networks:
      - ansible

networks:
  ansible:
    driver: bridge